### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by JoshuaSBrown** [joeyelk/MD-Structure-Factor#15]
@bencoscia and @joeyelk you guys are the ones who built it do you want to decide on a Licence? If you want the package to be usable by everyone I would suggest the MIT license.

**Comment by bencoscia** [comment]
MIT sounds good to me

**Comment by JoshuaSBrown** [comment]
@joeyelk I'm going to guess that you don't care for the most part. If you do let me know and we will change it.

**Comment by JoshuaSBrown** [comment]
You guys might want to add your name to the license file.

**Comment by joeyelk** [comment]
MIT License sounds good.
